### ISSUE TITLE
make: Nothing to be done for 'folder'

### ISSUE THREAD

**Issue by fat-kid** [vghost2008/sportstrack#3]
I try to use the comman that "make ./gmc D:/code/tracking/code/SportsMOT-main/sportsmot_publish/dataset/basketball/train/*"
but get nothing to be done for ....
I wonder if there were something wrong, the dataset is part of the SportsMOT and it contain the img1 folder and gt folder and seqinfo.ini in a folder...
the result is below...
![image](https://github.com/vghost2008/sportstrack/assets/42697256/1ad93a4d-e704-4082-813c-bccbde84b833)
 hopping your reply and give me some advise, thank you very much!!!

**Comment by vghost2008** [comment]
You need build gmc first, Each line below is a separate instruction

> cd gmc
> mkdir build
> cd build
> cmake ..
> make
> ./gmc ${SPORTSTRACK_ROOT}/data/sportsmot_publish/dataset/test/*   #this will generate a gmc.txt file in each input directorys
> ./gmc ${SPORTSTRACK_ROOT}/data/sportsmot_publish/dataset/val/* 


All instructions have only been tested on ubuntu 18.04.
